### ISSUE TITLE
Auto show autocomplete-list without press ctrl+space

### ISSUE THREAD

**Issue by syswow** [glymehrvrd/CppYCM#3]
Hello, 
How can I make the autocomplete-list auto show without press ctrl+space?

**Comment by glymehrvrd** [comment]
It should show automatically by default, did you set `auto_complete` to `true` in sublime configuration?

**Comment by syswow** [comment]
auto_complete has been set to true.

**Comment by glymehrvrd** [comment]
Can sublimetext show prompt editing other fileformat? You may look at the console of sublimetext by pressing `ctrl+``` to find out what's wrong. I can't provide a solution since everything works fine on my computer.

**Comment by syswow** [comment]
after I set auto_complete_triggers to trigger '.',  it works well now. Thanks!
