### ISSUE TITLE
the installation is faillure and when i open sublime, it reminds me sth. like "Ycmd is not found"

### ISSUE THREAD

**Issue by dollarzhaole** [glymehrvrd/CppYCM#7]
I'm so sorry to ask the question~
I'm know little about the YCMD, and found nothing about the YCMD on sublime on the Internet~
Firstly, I install the package by the package control. But I found nothing about the package(C++YouCompleteMe) in the dir (C:\Users\MyName\AppData\Roaming\Sublime Text 3\Packages\)
Then, I follow the https://github.com/ivankoster/SublimeYouCompleteMe#installation-for-64bit-windows
after that, the files in the dir(C:\Users\MyName\AppData\Roaming\Sublime Text 3\Packages\C++YouCompleteMe) are list as follows:
commands\
lib\
listeners\
ycmd\
C++YouCompleteMe.sublime-settings
LICENSE
Default (Linux).sublime-keymap
Main.sublime-menu    
Default (Linux).sublime-mousemap
README.md
Default.sublime-commands
ErrorPanel.tmLanguage
cppycmcompletion.py

In the ycmd dir, the files are list as follows:
clang_includes\
third_party\
ycmd\
CONTRIBUTING.md
README.md
libclang.dll
ycm_client_support.pyd
ycm_core.pyd
COPYING.txt

And int the C++YouCompleteme setting, I set that
"ycmd_path": "Packages/C++YouCompleteMe/ycmd",

But when I start the sublime, the error box is shown like this:
![Uploading 捕获.PNG . . .]()

My problems are that
1. Did I miss some steps to install the package?
2. should i start YCM server when i want to use the package in sublime, if so, how can i start the server~~~~(I'm so sorry to ask the question like that, because i'm know little about ycm and find nothing on the Internet about how to start ycmd without vim)

Thank you very much for your help~

**Comment by dollarzhaole** [comment]
I solve the problem with the absolutely path of the ycmd dir.
So close the issue

**Comment by glymehrvrd** [comment]
Windows is not a tested platform, but it should work if correctly complied ycmd server.
