### ISSUE TITLE
RuntimeError: waited for the server for 5 seconds, aborting

### ISSUE THREAD

**Issue by dollarzhaole** [glymehrvrd/CppYCM#8]
Exception in thread LoadExtraConfAsync:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "C:\Users\dollar\AppData\Roaming\Sublime Text 3\Packages\C++YouCompleteMe\listeners\loadextraconf.py", line 22, in load_extra_conf_func
    server.WaitUntilReady()
  File "C:\Users\dollar\AppData\Roaming\Sublime Text 3\Packages\C++YouCompleteMe\lib\ycmd_handler.py", line 179, in WaitUntilReady
    MAX_SERVER_WAIT_TIME_SECONDS))
RuntimeError: waited for the server for 5 seconds, aborting

Should I start the Ycm server manually? Or the '.ycm_extra_conf.py' file should be in a dir?
I put the '.ycm_extra_conf.py' file in the same dir with my .cpp file, I know youcompleteme with vim should do that

**Comment by glymehrvrd** [comment]
It seems your ycmd server didn't repond to the 'ready' request. What ycmd server did you use?

**Comment by dollarzhaole** [comment]
Thanks for you answer, I'm really appreciate it.
I use the ycmd server as the page(https://github.com/ivankoster/SublimeYouCompleteMe#installation-for-64bit-windows) says.
after that, the files are list as follows:
![default](https://cloud.githubusercontent.com/assets/4970307/7360888/0888a644-ed83-11e4-9f06-512d3543aa11.PNG)
![1](https://cloud.githubusercontent.com/assets/4970307/7360900/3c5ebd3c-ed83-11e4-9245-bab7f18a473d.PNG)

**Comment by dollarzhaole** [comment]
And my setting is
{
    "python_path": "C:/Python27/python.exe",
    "ycmd_path": "C:/Users/dollar/AppData/Roaming/Sublime Text 3/Packages/C++YouCompleteMe/server/ycmd",
    "highlight_errors_on_save": false,
    "select_after_goto": false,
    "error_panel_syntax_file": "C:/Users/dollar/AppData/Roaming/Sublime Text 3/Packages/C++YouCompleteMe/ErrorPanel.tmLanguage"
}

**Comment by glymehrvrd** [comment]
There are something wrong with your ycmd server.
First, try removing the line `22` in `loadextraconf.py`. If that still not works, you can use a web-sniffer tool like `WireShark` to inspect the requests sent to the ycmd server. There should be one request sent to `/ready`, please post the details on that request so I can find out what went wrong.
![screenshot from 2015-04-28 09 30 00](https://cloud.githubusercontent.com/assets/732769/7361416/6db560e6-ed8a-11e4-9833-73c7301206a7.png)

**Comment by dollarzhaole** [comment]
Thank you very much, you have helped me solved the problem.
It totally works!  (^_^)
![image](https://cloud.githubusercontent.com/assets/4970307/7386486/36be6e2c-ee87-11e4-9a00-34724044ace4.png)
I'm really appreciate your help.
Thanks again.
